displayName=Enhanced
author=DevOldSchool
description=Optional gameplay information enhancements for Old School RuneScape
tags=enhanced,npc,inspect,wiki
version=
plugins=com.enhanced.EnhancedPlugin
build=standard
